version: '3.1'

services:
  wallet-tracking-database:
    image: postgres
    container_name: wallet-tracking-database
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
